### ISSUE TITLE
⌨️ Change from Source Sans Pro to Inter to leverage variable font weights

### ISSUE THREAD

**Issue by xdesro** [leviboenish/portfolio-2019#3]
Initially we used Untitled Sans, which I understand you're not tryna spend on licensing right now. Instead I would use [Inter](https://rsms.me/inter/) _(surprise, surprise),_ because it's available as a variable font and you can much more accurately reflect the lighter weights that are used stylistically throughout the design.

```
@import url('https://rsms.me/inter/inter.css');
html { font-family: 'Inter', sans-serif; }
@supports (font-variation-settings: normal) {
  html { font-family: 'Inter var', sans-serif; }
}
```

**Comment by leviboenish** [comment]
Updated
