### ISSUE TITLE
🖼 Background image is missing

### ISSUE THREAD

**Issue by xdesro** [leviboenish/portfolio-2019#4]
It might not seem like a big thing but the texture added by that background image is gonna provide a lot of visual lift, and give purpose to the negative space on the site. It's exportable from the Figma file, but let me know if I can help get you the resource in a diff format, etc.

Some sort of cute `background-attachment` effect here will be v nice. The quickest one to ship is just doing a fixed background, but we should look into a drifty/parallaxed effect down the road.

**Comment by leviboenish** [comment]
done and done
